- name: Add NVIDIA package repository key
  ansible.builtin.get_url:
    url: https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2404/x86_64/cuda-keyring_1.1-1_all.deb
    dest: /tmp/cuda-keyring.deb

- name: Install CUDA keyring package using dpkg
  ansible.builtin.apt:
    deb: /tmp/cuda-keyring.deb
    state: present
    force: yes  # Optional - Ensures the package gets installed even if dependencies are not met

- name: Update apt repository cache
  ansible.builtin.apt:
    update_cache: yes

- name: Install NVIDIA drivers
  ansible.builtin.apt:
    name: cuda-drivers
    state: present

- name: Install CUDA Toolkit
  ansible.builtin.apt:
    name: cuda-toolkit-12-6
    state: present

- name: Remove temporary CUDA keyring package
  ansible.builtin.file:
    path: /tmp/cuda-keyring.deb
    state: absent
