- name: Deploy Ubuntu Cloud Image and Set Up VM
  hosts: localhost
  become: true
  vars:
    vm_name: "vm01"
    interface: "ens3"
    ip_address: "192.168.122.101"
    ram: 4096
    vcpus: 4
    disk_size: "50G"
    mac_address: "52:54:00:10:9a:cd"
    vm_username: "ubuntu"
    vm_password: "ubuntu"
    download_image: true
  roles:
    - download_image
    - configure_cloud_init_iso
    - create_vm
    - probing_vm

- name: Configure and Install Software on VM
  hosts: vm01
  become: true
  gather_facts: true
  roles:
    - install_xfce
    - install_vnc
    - install_miniforge
    - install_cuda
