---

collections:
  # Install a collection from Ansible Galaxy.
  - name: community.general
    version: ">=7.0.0"
    source: https://galaxy.ansible.com
  - name: ansible.posix
    version: ">=1.5.0"
    source: https://galaxy.ansible.com
  - name: community.docker
    version: ">=4.0.0"
    source: https://galaxy.ansible.com
  - name: community.libvirt
    version: ">=1.3.0"
    source: https://galaxy.ansible.com
  - name: community.crypto
    version: ">=2.22.1"
    source: https://galaxy.ansible.com
