- name: Get current (non-root) user's home directory
  ansible.builtin.command: echo $HOME
  register: user_home
  changed_when: false
  become: false

- name: Check if SSH public key exists (for non-root user)
  ansible.builtin.stat:
    path: "{{ user_home.stdout }}/.ssh/id_rsa.pub"
  register: ssh_key_stat
  become: false

- name: Generate SSH key if not present
  community.crypto.openssh_keypair:
    path: "{{ user_home.stdout  }}/.ssh/id_rsa"
    type: rsa
    size: 2048
  when: not ssh_key_stat.stat.exists

- name: Create cloud-init network configuration
  ansible.builtin.template:
    src: network-config.j2
    dest: "/tmp/{{ vm_name }}-network-config"
    mode: '0600'

- name: Create cloud-init user-data configuration
  ansible.builtin.template:
    src: user-data.j2
    dest: "/tmp/{{ vm_name }}-user-data"
    mode: '0600'
  become: false

- name: Create cloud-init meta-data configuration
  ansible.builtin.template:
    src: meta-data.j2
    dest: "/tmp/{{ vm_name }}-meta-data"
    mode: '0600'

- name: Create cloud-init ISO
  ansible.builtin.command:
    cmd: |
      cloud-localds -v --network-config=/tmp/{{ vm_name }}-network-config \
      /var/lib/libvirt/images/{{ vm_name }}-seed.qcow2 \
      /tmp/{{ vm_name }}-user-data /tmp/{{ vm_name }}-meta-data
    creates: "/var/lib/libvirt/images/{{ vm_name }}-seed.qcow2"
  register: cloud_init_result
  changed_when: cloud_init_result.rc == 0
