- name: Ensure image directory exists
  file:
    path: /var/lib/libvirt/images
    state: directory
    owner: libvirt-qemu
    group: kvm
    mode: '0755'

- name: Download Ubuntu cloud image
  get_url:
    url: "https://cloud-images.ubuntu.com/{{ ubuntu_release }}/current/{{ ubuntu_release }}-server-cloudimg-amd64.img"
    dest: "/var/lib/libvirt/images/{{ ubuntu_release }}-server-cloudimg-amd64.img"
    use_proxy: yes
  when: download_image | default(true)

- name: Set permissions for the image
  file:
    path: "/var/lib/libvirt/images/{{ ubuntu_release }}-server-cloudimg-amd64.img"
    owner: libvirt-qemu
    group: kvm
    mode: '0644'
