- name: Ensure image directory exists
  file:
    path: /var/lib/libvirt/images
    state: directory
    owner: libvirt-qemu
    group: kvm
    mode: '0755'

- name: Download Ubuntu cloud image
  get_url:
    url: "https://cloud-images.ubuntu.com/jammy/current/jammy-server-cloudimg-amd64.img"
    dest: /var/lib/libvirt/images/jammy-server-cloudimg-amd64.img
    use_proxy: yes
  when: download_image|default(true)

- name: Set permissions for the image
  file:
    path: /var/lib/libvirt/images/jammy-server-cloudimg-amd64.img
    owner: libvirt-qemu
    group: kvm
    mode: '0644'
