vm_name: "vm"
vm_username: "ubuntu"
interface: "ens3"
ip_address: "192.168.2.2"
ram: 4096
vcpus: 4
disk_size: "70G"
mac_address: "52:54:00:10:9a:cd"
download_image: true
ubuntu_release: "noble"
os_variant: "ubuntu24.04"
